---
title: "Baseball Scrape"
author: "Adam Chapnik"
date: "11/5/2018"
output: html_document
---

```{r include=FALSE}
library(rvest)
library(dplyr)
library(magrittr)
library(reshape2)
library(readr)
library(retrosheet)
library(stringr)
```

I will be scraping the major aggregate statistics from Baseball-Reference.com for every pitcher and batter who played a minimum of one game in the 2019 MLB season.


```{r}
main_url <- "https://www.baseball-reference.com/teams/#all_teams_active"
```

```{r}
## Team URLs
# Open main_url and navigate to interesting part of the page:
main_page <- read_html(main_url)
teams_html <- html_nodes(main_page, "#teams_active .left a")

# From the interesting part, get the teams and URLs:
m_teams <- html_text(teams_html)

sub_urls <- html_attr(teams_html, "href")
m_urls <- paste0("https://www.baseball-reference.com", sub_urls)
team_urls <- paste0(m_urls, "2019.shtml")

team_urls <- team_urls %>% setdiff(. , "https://www.baseball-reference.com/teams/ANA/2019.shtml")
team_urls <- c(team_urls, "https://www.baseball-reference.com/teams/LAA/2019.shtml")
team_urls <- team_urls %>% setdiff(. , "https://www.baseball-reference.com/teams/FLA/2019.shtml")
team_urls <- c(team_urls, "https://www.baseball-reference.com/teams/MIA/2019.shtml")
team_urls <- team_urls %>% setdiff(. , "https://www.baseball-reference.com/teams/TBD/2019.shtml")
team_urls <- c(team_urls, "https://www.baseball-reference.com/teams/TBR/2019.shtml")
```

```{r}
#Active pitchers#
pitchers_urls <- function(url){
  player_page <- read_html(url)
  pitcher_html <- html_nodes(player_page, "#team_pitching a")
  
  subs <- html_attr(pitcher_html, "href")
  player_urls <- paste0("https://www.baseball-reference.com", subs)

  return(player_urls)
}
x <- lapply(team_urls, pitchers_urls)
# Gives url for every active pitcher
all.pitchers <- c(x[[1]], x[[2]], x[[3]], x[[4]], x[[5]], x[[6]], x[[7]], x[[8]], x[[9]], x[[10]], x[[11]], x[[12]], x[[13]], x[[14]], x[[15]], x[[16]], x[[17]], x[[18]], x[[19]], x[[20]], x[[21]], x[[22]], x[[23]], x[[24]], x[[25]], x[[26]], x[[27]], x[[28]], x[[29]], x[[30]])
length(all.pitchers)
```


```{r}
#Scrape public table
get.standard.stats <- function(url){
  stats_page <- read_html(url) 
  stats_html <- html_nodes(stats_page, "#pitching_standard tbody .right , #pitching_standard tbody .left")
  a <- html_text(stats_html)
  x <- matrix(a, nrow = 35)
  x <- t(x)
  stats_html <- html_nodes(stats_page, "#pitching_standard th.poptip")
  a <- html_text(stats_html)
  colnames(x) <- a
  stats_html <- html_nodes(stats_page, "h1 span")
  Name <- html_text(stats_html)
  x <- cbind(Name, x)
  x <- x[,-c(5,36)]
  return(x)
}
pitchers <- lapply(all.pitchers, get.standard.stats) # list of matrices
compile <- function(x){
  y <- Reduce(rbind.data.frame, pitchers[1:x])
  return(y)
}
pitchers <- length(pitchers) %>% compile()
write.csv(pitchers, "pitchers.csv")
```


```{r}
#Active batters
batters_urls <- function(url){
  player_page <- read_html(url)
  batter_html <- html_nodes(player_page, "#team_batting a")
  
  subs <- html_attr(batter_html, "href")
  player_urls <- paste0("https://www.baseball-reference.com", subs)

  return(player_urls)
}
x <- lapply(team_urls, batters_urls)
# Gives url for every active batter
all.batters <- c(x[[1]], x[[2]], x[[3]], x[[4]], x[[5]], x[[6]], x[[7]], x[[8]], x[[9]], x[[10]], x[[11]], x[[12]], x[[13]], x[[14]], x[[15]], x[[16]], x[[17]], x[[18]], x[[19]], x[[20]], x[[21]], x[[22]], x[[23]], x[[24]], x[[25]], x[[26]], x[[27]], x[[28]], x[[29]], x[[30]])
```

```{r}
get.batters <- function(url){
  stats_page <- read_html(url) 
  stats_html <- html_nodes(stats_page, "h1 span")
  name <- html_text(stats_html)
  stats_html <- html_nodes(stats_page, "h1+ p")
  position <- html_text(stats_html)
  position <- gsub("\n  \n","",gsub("\n    Position:\n    ","",position))
  position <- gsub("\n    Positions:\n    ","",position)
  x <- cbind(url, name, position)
  return(x)
}
players <- lapply(all.batters, get.batters)
compile <- function(x){
  y <- Reduce(rbind.data.frame, players[1:x])
  return(y)
}
players <- length(players) %>% compile()
all.batters <- players %>% 
  filter(!str_detect(position, "Pitcher"))
all.batters <- as.vector(unlist(all.batters[1]))
```


```{r}
#Scrape public table batters
get.standard.stats <- function(url){
  stats_page <- read_html(url) 
  stats_html <- html_nodes(stats_page, "#batting_standard tbody .right , #batting_standard tbody .left")
  a <- html_text(stats_html)
  x <- matrix(a, nrow = 30)
  x <- t(x)
  stats_html <- html_nodes(stats_page, "#batting_standard .poptip")
  a <- html_text(stats_html)
  colnames(x) <- a
  stats_html <- html_nodes(stats_page, "h1 span")
  Name <- html_text(stats_html)
  x <- cbind(Name, x)
  x <- x[,-c(5,30,31)]
  return(x)
}
batters <- lapply(all.batters, get.standard.stats) # list of matrices
compile <- function(x){
  y <- Reduce(rbind.data.frame, batters[1:x])
  return(y)
}
batters <- length(batters) %>% compile()
write.csv(batters, "batters.csv")
```


THIS IS THE END OF THE AVAILABLE PITCHER DATA ON BASEBALL-REFERENCE.COM.


```{r}
## SEPARATE DATASET ##
# Game lineups and pitchers
  # Get lineup orders + pinch hitters by out number (x/54+)
  # Get pitchers and changes by out number (x/54+)
  # Get umpires + changes
"game" %>% getRetrosheet(2019)
```


Use the following link to find the following code: https://billpetti.github.io/2018-02-19-build-statcast-database-rstats/

```{r}
#Statcast datascrape
require(readr)
require(dplyr)
require(xml2)
require(magrittr)

dates_reduced <- read_csv("https://raw.githubusercontent.com/BillPetti/baseball_research_notebook/master/dates_statcast_build.csv")
dates_reduced_two <- read_csv("dates_reduced_two.csv")
dates_reduced <- rbind(dates_reduced, dates_reduced_two)

x2008season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2008)

x2009season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2009)

x2010season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2010)

x2011season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2011)

x2012season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2012)

x2013season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2013)

x2014season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2014)

x2015season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2015)

x2016season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2016)

x2017season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2017)

x2018season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2018)

x2019season <- dates_reduced %>%
  filter(substr(GameDate, 1, 4) == 2019)

scrape_statcast_savant_pitcher_date <- function(start_date, end_date) {
  
  # extract year
  year <- substr(start_date, 1,4)
  
  # Base URL.
  url <- paste0("https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7C&hfC=&hfSea=",year,"%7C&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=",start_date,"&game_date_lt=",end_date,"&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details&")
  
  payload <- utils::read.csv(url)
  
  if (length(payload$pitch_type) > 0) {
  
  # Clean up formatting.
  payload$game_date <- as.Date(payload$game_date, "%Y-%m-%d")
  payload$des <- as.character(payload$des)
  payload$game_pk <- as.character(payload$game_pk) %>% as.numeric()
  payload$on_1b <- as.character(payload$on_1b) %>% as.numeric()
  payload$on_2b <- as.character(payload$on_2b) %>% as.numeric()
  payload$on_3b <- as.character(payload$on_3b) %>% as.numeric()
  payload$release_pos_x <- as.character(payload$release_pos_x) %>% as.numeric()
  payload$release_pos_z <- as.character(payload$release_pos_z) %>% as.numeric()
  payload$release_pos_y <- as.character(payload$release_pos_y) %>% as.numeric()
  payload$pfx_x <- as.character(payload$pfx_x) %>% as.numeric()
  payload$pfx_z <- as.character(payload$pfx_z) %>% as.numeric()
  payload$hc_x <- as.character(payload$hc_x) %>% as.numeric()
  payload$hc_y <- as.character(payload$hc_y) %>% as.numeric()
  payload$woba_denom <- as.character(payload$woba_denom) %>% as.numeric()
  payload$woba_value <- as.character(payload$woba_value) %>% as.numeric()
  payload$babip_value <- as.character(payload$babip_value) %>% as.numeric()
  payload$iso_value <- as.character(payload$iso_value) %>% as.numeric()
  payload$plate_z <- as.character(payload$plate_z) %>% as.numeric()
  payload$plate_x <- as.character(payload$plate_x) %>% as.numeric()
  payload$vx0 <- as.character(payload$vx0) %>% as.numeric()
  payload$vy0 <- as.character(payload$vy0) %>% as.numeric()
  payload$vz0 <- as.character(payload$vz0) %>% as.numeric()
  payload$ax <- as.character(payload$ax) %>% as.numeric()
  payload$ay <- as.character(payload$ay) %>% as.numeric()
  payload$az <- as.character(payload$az) %>% as.numeric()
  payload$sz_top <- as.character(payload$sz_top) %>% as.numeric()
  payload$sz_bot <- as.character(payload$sz_bot) %>% as.numeric()
  payload$hit_distance_sc <- as.character(payload$hit_distance_sc) %>% as.numeric()
  payload$launch_speed <- as.character(payload$launch_speed) %>% as.numeric()
  payload$launch_speed_angle <- as.character(payload$launch_speed_angle) %>% as.numeric()
  payload$launch_angle <- as.character(payload$launch_angle) %>% as.numeric()
  payload$estimated_ba_using_speedangle <- as.character(payload$estimated_ba_using_speedangle) %>% as.numeric()
  payload$estimated_woba_using_speedangle <- as.character(payload$estimated_woba_using_speedangle) %>% as.numeric()
  payload$effective_speed <- as.character(payload$effective_speed) %>% as.numeric()
  payload$release_speed <- as.character(payload$release_speed) %>% as.numeric()
  payload$zone <- as.character(payload$zone) %>% as.numeric()
  payload$release_spin_rate <- as.character(payload$release_spin_rate) %>% as.numeric()
  payload$release_extension <- as.character(payload$release_extension) %>% as.numeric()
  payload$barrel <- with(payload, ifelse(launch_angle <= 50 & launch_speed >= 98 & launch_speed * 1.5 - launch_angle >= 117 & launch_speed + launch_angle >= 124, 1, 0))
  payload$home_team <- as.character(payload$home_team)
  payload$away_team <- as.character(payload$away_team)
  
  return(payload)
  }
  
  else {
    vars <- names(payload)
    df <- lapply(vars, function(x) x <- NA)
    names(df) <- names(payload)
    payload_na <- bind_rows(df)
  
    return(payload_na)
    
    Sys.sleep(sample(x = runif(20, min = .01, max = 1), size = 1))
  }
}

x2008data <- x2008season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

(missing_2008 <- x2008data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2009data <- x2009season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2009 <- x2009data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2010data <- x2010season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2010 <- x2010data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2011data <- x2011season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2011 <- x2011data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2012data <- x2012season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2012 <- x2012data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2013data <- x2013season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2013 <- x2013data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2014data <- x2014season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2014 <- x2014data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2015data <- x2015season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2015 <- x2015data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data1 <- x2016season[c(1:20),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20161 <- x2016data1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data2 <- x2016season[c(21:40),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20162 <- x2016data2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data3 <- x2016season[c(41:60),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20163 <- x2016data3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data4 <- x2016season[c(61:80),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20164 <- x2016data4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data5 <- x2016season[c(81:100),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20165 <- x2016data5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data6 <- x2016season[c(101:120),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20166 <- x2016data6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data7 <- x2016season[c(121:140),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20167 <- x2016data7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data8 <- x2016season[c(141:160),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20168 <- x2016data8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data9 <- x2016season[c(161:162),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20169 <- x2016data9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data10 <- x2016season[c(163:164),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_201610 <- x2016data10 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data11 <- x2016season[c(165:166),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_201611 <- x2016data11 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

 x2016data12 <- x2016season[c(167:168),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_201612 <- x2016data12 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data13 <- x2016season[169,] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_201613 <- x2016data13 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data14 <- x2016season[170,] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_201614 <- x2016data14 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data15 <- x2016season[c(171:172),] %>% 
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_201615 <- x2016data15 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2016data <- rbind(x2016data1, x2016data2, x2016data3, x2016data4, x2016data5, x2016data6, x2016data7, x2016data8, x2016data9, x2016data10, x2016data11, x2016data12, x2016data13, x2016data14, x2016data15)


## 2017
x2017data1 <- x2017season[c(1:2),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20171 <- x2017data1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data1.1 <- x2017season[3,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20171.1 <- x2017data1.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data1.1.1 <- x2017season[c(4:5),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20171.1.1 <- x2017data1.1.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data1.2 <- x2017season[c(6:10),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20171.2 <- x2017data1.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data1.3 <- x2017season[c(11:20),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20171.3 <- x2017data1.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data2 <- x2017season[c(21:22),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20172 <- x2017data2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data2.1 <- x2017season[23,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20172.1 <- x2017data2.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data2.1.1 <- x2017season[24,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20172.1.1 <- x2017data2.1.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data2.1.2 <- x2017season[25,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20172.1.2 <- x2017data2.1.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data2.2 <- x2017season[c(26:30),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20172.2 <- x2017data2.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data2.3 <- x2017season[c(31:40),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20172.3 <- x2017data2.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data3 <- x2017season[c(41:50),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20173 <- x2017data3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data3.1 <- x2017season[c(51:55),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20173.1 <- x2017data3.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data3.2 <- x2017season[c(56:57),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20173.2 <- x2017data3.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data3.3 <- x2017season[58,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20173.3 <- x2017data3.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data3.4 <- x2017season[59,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20173.4 <- x2017data3.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data3.5 <- x2017season[60,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20173.5 <- x2017data3.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4 <- x2017season[61,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174 <- x2017data4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.1.1 <- x2017season[62,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.1.1 <- x2017data4.1.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.1.2 <- x2017season[63,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.1.2 <- x2017data4.1.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.1.3 <- x2017season[64,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.1.3 <- x2017data4.1.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.1.4 <- x2017season[65,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.1.4 <- x2017data4.1.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.2 <- x2017season[66,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.2 <- x2017data4.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.2.1 <- x2017season[67,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.2.1 <- x2017data4.2.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.2.2 <- x2017season[68,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.2.2 <- x2017data4.2.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.2.3 <- x2017season[c(69:70),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.2.3 <- x2017data4.2.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.3 <- x2017season[c(71:72),] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.3 <- x2017data4.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.3.1 <- x2017season[73,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.3.1 <- x2017data4.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.3.2 <- x2017season[74,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.3.2 <- x2017data4.3.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.3.3 <- x2017season[75,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.3.3 <- x2017data4.3.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.4 <- x2017season[76,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.4 <- x2017data4.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.5 <- x2017season[77,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.5 <- x2017data4.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.6 <- x2017season[78,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.6 <- x2017data4.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.7 <- x2017season[79,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.7 <- x2017data4.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data4.8 <- x2017season[80,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20174.8 <- x2017data4.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5 <- x2017season[81,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175 <- x2017data5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.1 <- x2017season[82,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.1 <- x2017data5.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.1.1 <- x2017season[83,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.1.1 <- x2017data5.1.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.1.2 <- x2017season[84,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.1.2 <- x2017data5.1.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.1.3 <- x2017season[85,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.1.3 <- x2017data5.1.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.1.4 <- x2017season[86,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.1.4 <- x2017data5.1.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.1.5 <- x2017season[87,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.1.5 <- x2017data5.1.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.2 <- x2017season[88,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.2 <- x2017data5.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.2.1 <- x2017season[89,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.2.1 <- x2017data5.2.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.2.2 <- x2017season[90,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.2.2 <- x2017data5.2.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.5 <- x2017season[91,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.5. <- x2017data5.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.5.1 <- x2017season[92,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.5.1 <- x2017data5.5.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.5.2 <- x2017season[93,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.5.2 <- x2017data5.5.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.6 <- x2017season[94,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.6. <- x2017data5.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.6.1 <- x2017season[95,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.6.1 <- x2017data5.6.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.6.2 <- x2017season[96,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.6.2 <- x2017data5.6.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.6.3 <- x2017season[97,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.6.3 <- x2017data5.6.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.7 <- x2017season[98,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.7 <- x2017data5.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.7.1 <- x2017season[99,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.7.1 <- x2017data5.7.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data5.7.2 <- x2017season[100,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20175.7.2 <- x2017data5.7.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6 <- x2017season[101,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176 <- x2017data6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.1 <- x2017season[102,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.1 <- x2017data6.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.2 <- x2017season[103,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.2 <- x2017data6.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.3 <- x2017season[104,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.3 <- x2017data6.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.4 <- x2017season[105,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.4 <- x2017data6.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.5 <- x2017season[106,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.5 <- x2017data6.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.6 <- x2017season[107,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.6 <- x2017data6.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.7 <- x2017season[108,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.7 <- x2017data6.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.8 <- x2017season[109,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.8 <- x2017data6.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.9 <- x2017season[110,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.9 <- x2017data6.9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.5 <- x2017season[111,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.5 <- x2017data6.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.6 <- x2017season[112,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.6 <- x2017data6.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.7 <- x2017season[113,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.7 <- x2017data6.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.8 <- x2017season[114,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.8 <- x2017data6.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.9 <- x2017season[115,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.9 <- x2017data6.9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.9.1 <- x2017season[116,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.9.1 <- x2017data6.9.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.9.2 <- x2017season[117,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.9.2 <- x2017data6.9.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.9.3 <- x2017season[118,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.9.3 <- x2017data6.9.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.9.4 <- x2017season[119,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.9.4 <- x2017data6.9.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data6.9.5 <- x2017season[120,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20176.9.5 <- x2017data6.9.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))


x2016data <- rbind(x2016data, x2016data1, x2016data2, x2016data3, x2016data4, x2016data5, x2016data6, x2016data7, x2016data8, x2016data9, x2016data10, x2016data11, x2016data12, x2016data13, x2016data14, x2016data15)


x2017data7 <- x2017season[121,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177 <- x2017data7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1 <- x2017season[122,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1 <- x2017data7.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.2 <- x2017season[123,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.2 <- x2017data7.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.3 <- x2017season[124,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.3 <- x2017data7.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.4 <- x2017season[125,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.4 <- x2017data7.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.5 <- x2017season[126,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.5 <- x2017data7.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.6 <- x2017season[127,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.6 <- x2017data7.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.7 <- x2017season[128,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.7 <- x2017data7.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.8 <- x2017season[129,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.8 <- x2017data7.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.9 <- x2017season[130,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.9 <- x2017data7.9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.1 <- x2017season[131,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.1 <- x2017data7.1.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.2 <- x2017season[132,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.2 <- x2017data7.1.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.3 <- x2017season[133,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.3 <- x2017data7.1.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.4 <- x2017season[134,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.4 <- x2017data7.1.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.5 <- x2017season[135,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.5 <- x2017data7.1.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.6 <- x2017season[136,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.6 <- x2017data7.1.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.7 <- x2017season[137,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.7 <- x2017data7.1.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.8 <- x2017season[138,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.8 <- x2017data7.1.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.1.9 <- x2017season[139,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.1.9 <- x2017data7.1.9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data7.2.2 <- x2017season[140,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20177.2.2 <- x2017data7.2.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.1 <- x2017season[141,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.1 <- x2017data8.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.2 <- x2017season[142,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.2 <- x2017data8.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.3 <- x2017season[143,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.3 <- x2017data8.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.4 <- x2017season[144,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.4 <- x2017data8.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.5 <- x2017season[145,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.5 <- x2017data8.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.6 <- x2017season[146,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.6 <- x2017data8.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.7 <- x2017season[147,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.7 <- x2017data8.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.8 <- x2017season[148,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.8 <- x2017data8.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9 <- x2017season[149,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9 <- x2017data8.9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.1 <- x2017season[150,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.1 <- x2017data8.9.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.2 <- x2017season[151,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.2 <- x2017data8.9.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.3 <- x2017season[152,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.3 <- x2017data8.9.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.4 <- x2017season[153,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.4 <- x2017data8.9.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.5 <- x2017season[154,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.5 <- x2017data8.9.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.6 <- x2017season[155,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.6 <- x2017data8.9.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.7 <- x2017season[156,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.7 <- x2017data8.9.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.8 <- x2017season[157,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.8 <- x2017data8.9.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.9 <- x2017season[158,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.9 <- x2017data8.9.9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.9.1 <- x2017season[159,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.9.1 <- x2017data8.9.9.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data8.9.9.2 <- x2017season[160,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20178.9.9.2 <- x2017data8.9.9.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9 <- x2017season[161,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179 <- x2017data9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.1 <- x2017season[162,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.1 <- x2017data9.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.2 <- x2017season[163,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.2 <- x2017data9.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.3 <- x2017season[164,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.3 <- x2017data9.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.4 <- x2017season[165,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.4 <- x2017data9.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.5 <- x2017season[166,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.5 <- x2017data9.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.6 <- x2017season[167,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.6 <- x2017data9.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.7 <- x2017season[166,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.7 <- x2017data9.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.8 <- x2017season[167,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.8 <- x2017data9.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9 <- x2017season[168,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9 <- x2017data9.9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.1 <- x2017season[169,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.1 <- x2017data9.9.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.2 <- x2017season[170,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.2 <- x2017data9.9.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.3 <- x2017season[171,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.3 <- x2017data9.9.3 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.4 <- x2017season[172,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.4 <- x2017data9.9.4 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.5 <- x2017season[173,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.5 <- x2017data9.9.5 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.6 <- x2017season[174,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.6 <- x2017data9.9.6 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.7 <- x2017season[175,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.7 <- x2017data9.9.7 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.8 <- x2017season[176,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.8 <- x2017data9.9.8 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.9 <- x2017season[177,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.9 <- x2017data9.9.9 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.9.1 <- x2017season[178,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.9.1 <- x2017data9.9.9.1 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data9.9.9.2 <- x2017season[179,] %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_20179.9.9.2 <- x2017data9.9.9.2 %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2017data <- rbind(x2017data1, x2017data1.1, x2017data1.1.1, x2017data1.2, x2017data1.3, x2017data2, x2017data2.1, x2017data2.1.1, x2017data2.1.2, x2017data2.2, x2017data2.3, x2017data3, x2017data3.1, x2017data3.2, x2017data3.3, x2017data3.4, x2017data3.5, x2017data4, x2017data4.1.1, x2017data4.1.2, x2017data4.1.3, x2017data4.1.4, x2017data4.2, x2017data4.2.1, x2017data4.2.2, x2017data4.2.3, x2017data4.3, x2017data4.3.1, x2017data4.3.2, x2017data4.3.3, x2017data4.4, x2017data4.5, x2017data4.6, x2017data4.7, x2017data4.8, x2017data5, x2017data5.1, x2017data5.1.1, x2017data5.1.2, x2017data5.1.3, x2017data5.1.4, x2017data5.1.5, x2017data5.2, x2017data5.2.1, x2017data5.2.2, x2017data5.5, x2017data5.5.1, x2017data5.5.2, x2017data5.6, x2017data5.6.1, x2017data5.6.2, x2017data5.6.3, x2017data5.7, x2017data5.7.1, x2017data5.7.2, x2017data6, x2017data6.1, x2017data6.2, x2017data6.3, x2017data6.4, x2017data6.5, x2017data6.6, x2017data6.7, x2017data6.8, x2017data6.9, x2017data6.9.1, x2017data6.9.2, x2017data6.9.3, x2017data6.9.4, x2017data6.9.5, x2017data8.1, x2017data8.2, x2017data8.3, x2017data8.4, x2017data8.5, x2017data8.6, x2017data8.7, x2017data8.8, x2017data8.9, x2017data8.9.1, x2017data8.9.2, x2017data8.9.3, x2017data8.9.4, x2017data8.9.5, x2017data8.9.6, x2017data8.9.7, x2017data8.9.8, x2017data8.9.9, x2017data8.9.9.1, x2017data8.9.9.2, x2017data9, x2017data9.1, x2017data9.2, x2017data9.3, x2017data9.4, x2017data9.5, x2017data9.6, x2017data9.7, x2017data9.8, x2017data9.9, x2017data9.9.1, x2017data9.9.2, x2017data9.9.3, x2017data9.9.4, x2017data9.9.5, x2017data9.9.6, x2017data9.9.7, x2017data9.9.8, x2017data9.9.9, x2017data9.9.9.1, x2017data9.9.9.2)
```


```{r}
# RUN + TEST #
x2018data <- x2018season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2018 <- x2018data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))

x2019data <- x2019season %>%
  group_by(start_date) %>%
  do(scrape_statcast_savant_pitcher_date(.$start_date, .$end_date)) %>%
  ungroup() %>%
  select(-start_date)

gc()

(missing_2019 <- x2019data %>%
  filter(is.na(pitch_type)) %>%
  distinct(game_date) %>%
  select(game_date))
```


```{r}
statcast_bind <- rbind(x2008data, x2009data, x2010data, x2011data, x2012data, x2013data, x2014data, x2015data, x2016data, x2017data, x2018data, x2019data)

statcast_bind$game_date <- as.character(statcast_bind$game_date)

statcast_bind <- statcast_bind %>%
  arrange(game_date)

statcast_bind <- statcast_bind %>%
  filter(!is.na(game_date))

write.csv(statcast_bind, "Statcast_2008_2019.csv")

statcast_bind
```


Continue... adjust data, clean, and add variables. Also, use FanGraphs for special data.


